# General
title: Star of Wonder
description: [ SoW description]
url: "http://sufjan.info"
permalink: /:categories/:title

# Build settings
markdown: kramdown

# Sass directory
sass:
  sass_dir: /src/styles/_sass